- name: setup mysql database server
  hosts: database
  become: yes

  tasks:
    - name: install mysql server
      ansible.builtin.apt:
        name: 
          - mysql-server
          - mysql-client
          - unzip
        state: present
        update_cache: yes

    - name: enable and start mysql service
      ansible.builtin.service:
        name: mysql
        state: started
        enabled: yes

    - name: Set MySQL root password
      ansible.builtin.shell: |
        mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'ExpenseApp@1';"
      args:
        executable: /bin/bash
      ignore_errors: yes

    - name: Allow remote connections
      ansible.builtin.lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'

    - name: Restart MySQL service
      ansible.builtin.service:
        name: mysql
        state: restarted

    - name: Install MySQL client
      ansible.builtin.apt:
        name: mysql-client
        state: present

    - name: Download backend schema
      ansible.builtin.get_url:
        url: https://expense-artifacts.s3.amazonaws.com/expense-backend-v2.zip
        dest: /tmp/backend.zip

    - name: Extract backend schema
      ansible.builtin.unarchive:
        src: /tmp/backend.zip
        dest: /tmp
        remote_src: yes

    - name: Load backend schema
      ansible.builtin.shell: |
        mysql -uroot -pExpenseApp@1 < /tmp/schema/backend.sql
      args:
        executable: /bin/bash
